### ISSUE TITLE
Discussion 1

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#1]
Why the interface between adding songs to an album and to a playlist are different?

**Comment by mr-sudaca** [comment]
good question, closely related to https://github.com/mr-sudaca/yama/issues/3. I thought of "adding songs" to a playlist as an interface to adding existing songs to the list, and to add new songs to an album on the albums interface. Thinking of this, maybe both interfaces might work the same way (passing a list of existing song ids to the album/playlist) and create an endpoint to add songs in songs api

**Comment by alex-nexus** [comment]
close for now
