### ISSUE TITLE
Handle delete non-existing entities

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#10]
1. How would you handle if API trying to delete a song, album, or artist that doesn't exist or already deleted?
2. How would you handle if API trying to delete a song from a playlist or an album, that's not associated with the playlist or album?

**Comment by mr-sudaca** [comment]
for both questions, I'll let grape return the whole error trace (ActiveRecord::RecordNotFound) and send the error to a full stack error monitor, like airbrake or rollbar

**Comment by alex-nexus** [comment]
ok. I will close this ticket for now.
