### ISSUE TITLE
Any additional improvements? (bonus)

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#12]
If you are free to improve this project in any way you like, what would you do?
Some hints:
1. Any good common gems to add?
2. Any additional tests you would like to add?
3. etc

**Comment by mr-sudaca** [comment]
1. 
- An error reporting gem (rollbar, airbrake)
- A faster serializer, there's a gem called Oj that works really great.
- Capistrano, to help me to deploy the whole thing

2. Yeah, I haven't added test for caching and authorization, I've been adding code at the same time I read grape docs to see how to implement both thing "properly"

3. I would address your concern about the data model, I would create a many-to-many relationship between songs and artists and songs and albums, and i'd update interfaces

**Comment by alex-nexus** [comment]
sounds good. Good suggestions on the gems and oj.

If you plan to work on the data model enhancements, please create a separate issue. I would close this ticket for now.

**Comment by mr-sudaca** [comment]
@alex-nexus  Related issued https://github.com/mr-sudaca/yama/issues/19

**Comment by alex-nexus** [comment]
close this for now.
