### ISSUE TITLE
Caching (bonus)

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#5]
You mentioned about caching in your email. 
1. How would you approach about caching and at which level?
2. If you are in charge of performance tuning, what would be the top 3 APIs you would add cache to?

**Comment by mr-sudaca** [comment]
1. I'd use a no-sql db, like redis, to store api responses and return them as cached responses. Example, `GET /api/artists`. In this case, the api will store the response from this call using the key `/api/artists`. If another artist (or album) is added/deleted/update, the cache will be invalidated for this endpoint. I'd implement this as a set of helper methods in `api.rb`

2. 
```
/api/albums
/api/artists
/api/playlists
```

but, basically, I'd add cache to every `GET` endpoint


I'll address this and I'll post the pr as a follow up

**Comment by mr-sudaca** [comment]
Caching PR: https://github.com/mr-sudaca/yama/pull/17

**Comment by alex-nexus** [comment]
please close when merged

**Comment by alex-nexus** [comment]
close this for now
