### ISSUE TITLE
Performance Tuning

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#7]
I believe for GET albums, artists, and playlists APIs, returning the first 100 of the respective entities would result in many and slow queries. How would you approach in tuning the performance?

**Comment by mr-sudaca** [comment]
1. I'll remove that hardcoded limit. 
2. I'll cache those `GET` endpoints, see https://github.com/mr-sudaca/yama/issues/5#issuecomment-279472860

**Comment by alex-nexus** [comment]
ok, do you think the query can be optimized?

**Comment by mr-sudaca** [comment]
Absolutel, I can eager load associations on each one of those endpoints, like, on albums, I can eager load songs... i'll address that as well on a further PR

**Comment by alex-nexus** [comment]
awesome, looking forward to the pr

**Comment by alex-nexus** [comment]
close this for now
