### ISSUE TITLE
Data integrity discussion 2

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#8]
How would you handle when an API request to add or update a song to to an album that doesn't belong to the artist?

**Comment by mr-sudaca** [comment]
Songs are associated to an album, not to an artist, the song update endpoint doesn't ask for an artist

**Comment by alex-nexus** [comment]
Good point. It is my bad. So when updating a song to another album of a different artist, it means that the song belongs to another artist. In the real world, a song may need to associate with an artist independently from the album, but that's data model issue. Anyway, I will close this issue for now.
